### ISSUE TITLE
Lead-ins section: Irrelevant video used. Should have used the default titan video if none provided by client.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Peerless-Australia#10]
Per standards:
If no video is available, use this instead: http://www.youtube.com/v/whBe3u1FIms.

![image](https://cloud.githubusercontent.com/assets/11186313/6680715/df42e1fe-cc95-11e4-8e05-a8a545886291.png)

**Comment by roseliesromeo** [comment]
Video won't play.

![image](https://cloud.githubusercontent.com/assets/11186313/6727654/9be76be4-ce5e-11e4-9838-4b51d061be33.png)

**Comment by genesiscebudigital** [comment]
What Browser?

**Comment by roseliesromeo** [comment]
Video is now working good.
