### ISSUE TITLE
Gallery page: Album image is corrupted.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Peerless-Australia#100]
Samsung Tab3

![image](https://cloud.githubusercontent.com/assets/11186313/6747470/cbfc09aa-cf14-11e4-88e0-8355b5837a44.png)

**Comment by genesiscebudigital** [comment]
Not Sure

**Comment by roseliesromeo** [comment]
Exists again.

![image](https://cloud.githubusercontent.com/assets/11186313/6772870/90dff586-d142-11e4-9280-a74ba2616d9a.png)

**Comment by roseliesromeo** [comment]
Happens again in iTouch 5 (portrait view)

![image](https://cloud.githubusercontent.com/assets/11186313/6774060/2f64479a-d155-11e4-8b42-5f2cd0e3c47c.png)
