### ISSUE TITLE
Our Products page - Sidebar section:  Shouldn't we link the Enquire Now to the pop up form instead?

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Peerless-Australia#39]
Enquire Now will currently link to Contact Us page while the Contact Us will open a pop window for another form. Haven't we interchanged the implementation of the two buttons/links?

**Comment by genesiscebudigital** [comment]
Yes because the popup has a hidden field that generate title from products

**Comment by roseliesromeo** [comment]
What did you fix in this item then?
