### ISSUE TITLE
Gallery page: Layout for Compact and Extended albums are not designed similarly as the gallery page.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Peerless-Australia#41]
![image](https://cloud.githubusercontent.com/assets/11186313/6701896/ec385a60-cd5d-11e4-8f74-2f7b51a98084.png)

**Comment by genesiscebudigital** [comment]
I can't Design extended album similar to compact album . , thats is the nextgen default design

**Comment by roseliesromeo** [comment]
Extended album doesn't necessarily be the same as the Compact album.  As long as they are similar to the gallery images.

**Comment by roseliesromeo** [comment]
No change made. You only added another extended album.
