### ISSUE TITLE
Gallery page: Albums are overlapping.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Peerless-Australia#82]
iPad air (landscape)
Samsung Tab3 (landscape)
![image](https://cloud.githubusercontent.com/assets/11186313/6726096/bd9be3fc-ce4d-11e4-9d75-7449c5c68ce3.png)

**Comment by roseliesromeo** [comment]
![image](https://cloud.githubusercontent.com/assets/11186313/6745103/4eabdc54-ceed-11e4-8b33-3376d63598c5.png)

**Comment by roseliesromeo** [comment]
Still overlapping in Tab 3.

![image](https://cloud.githubusercontent.com/assets/11186313/6746639/e5f50978-cf06-11e4-8bdd-7c7344a261cd.png)

**Comment by genesiscebudigital** [comment]
I'm not sure . , don't have device here
