### ISSUE TITLE
Lead-ins section: Image doesn't exactly fit in the lead-ins container.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Peerless-Australia#83]
IE7 
![image](https://cloud.githubusercontent.com/assets/11186313/6726213/c43429c0-ce4f-11e4-9d3e-75b0ff6559f6.png)

**Comment by roseliesromeo** [comment]
Not fixed yet.

**Comment by genesiscebudigital** [comment]
try to clear cache . , it is ok in my end

**Comment by roseliesromeo** [comment]
It looks the same in my end and I always clear cache before testing.

**Comment by roseliesromeo** [comment]
Still not fixed in IE7

**Comment by roseliesromeo** [comment]
Exists again in iTouch 5

**Comment by roseliesromeo** [comment]
Not fixed in landscape view.

**Comment by genesiscebudigital** [comment]
please provide screen shot

**Comment by roseliesromeo** [comment]
iTouch 5 and iPad air 
landscape view

![image](https://cloud.githubusercontent.com/assets/11186313/6773838/f98c1470-d151-11e4-98af-2a18bbeb6c4e.png)

**Comment by roseliesromeo** [comment]
iPad air
![image](https://cloud.githubusercontent.com/assets/11186313/6774841/0b1600ce-d162-11e4-904b-25d31b049208.png)

Samsung Tab3
![image](https://cloud.githubusercontent.com/assets/11186313/6774843/10d356a6-d162-11e4-9d15-4c1e91336424.png)
